-- This script creates the MediaLibrary relationships schema. DO NOT MODIFY!

CREATE TABLE MEDIA_RELATIONSHIPS (
  LEFTID TEXT COLLATE NOCASE,
  LEFTTYPE TEXT COLLATE NOCASE,
  RIGHTID TEXT COLLATE NOCASE,
  RIGHTTYPE TEXT COLLATE NOCASE,
  
  CONSTRAINT MEDIA_RELATIONSHIPS_UK UNIQUE (LEFTID, LEFTTYPE, RIGHTID, RIGHTTYPE),
  CONSTRAINT MEDIA_RELATIONSHIPS_LEFTID_FK FOREIGN KEY (LEFTID) REFERENCES MEDIA_ITEMS (MEDIA_ITEM_ID) ON DELETE CASCADE
);
CREATE INDEX MEDIA_RELATIONSHIPS_LEFTID_IDX ON MEDIA_RELATIONSHIPS(LEFTID);
CREATE INDEX MEDIA_RELATIONSHIPS_RIGHTID_IDX ON MEDIA_RELATIONSHIPS(RIGHTID);
